apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {name}
  namespace: {namespace}
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {name}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {name}