# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Cluster
# metadata:
#   name: ha-vc
#   namespace: ha-vcluster
# spec:
#   controlPlaneRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
#     kind: VCluster
#     name: ha-vc
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
#     kind: VCluster
#     name: ha-vc
# ---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {name}
  namespace: {namespace}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    # chart:
    #   name: null
    #   repo: null
    #   version: null
    values: |
      enableHA: true
      syncer:
        replicas: 3
      etcd:
        replicas: 3
      controller:
        replicas: 3
      api:
        replicas: 3
      coredns:
        replicas: 3
      service:
        type: NodePort
  kubernetesVersion: 1.27.0
# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: newcluster-quota
#   namespace: ha-vcluster
# spec:
#   hard:
#     pods: "10"
#     services: "10"
#     configmaps: "10"
#     persistentvolumeclaims: "10"
#     replicationcontrollers: "20"
#     secrets: "10"
#     services.loadbalancers: "5"
#     services.nodeports : "5"



